### ISSUE TITLE
技術書典15「ChatGPTアプリを作って学ぶReact」で気づいた点について

### ISSUE THREAD

**Issue by yamap55** [aion0721/gisho15-errata#1]
はじめまして
技術書典15で「ChatGPTアプリを作って学ぶReact」を購入させて頂き、読ませて頂きました。
気づいた点がいくつかありますので報告させて頂きます。

## タイポと思われる点

- p.19 最下部
  - 「この分は」 -> 「この文は」
- p.27
  - 「handlePromptというものを用意しているの、」とあるが「で」が抜けている？

## 読んでいて気になった点

※個人の感想です

- p.ii（以外にも多数）
  - 「Github」 → 「GitHub」
  - サービス名なので公式表記が良いかと思いました

- p.2（以外にも多数）

  - 「Javascript」 → 「JavaScript」
  - 言語名なので公式表記が良いかと思いました
- p.6
  - ビルドという表現が使用されていますが、バックエンドでも使用しますし、デプロイは環境に配置するという理解なので少し違う気がしました
- p.7
  - 「Viteというやつ」という表現はもう少し変えても良いのかなと思いました
  - xxフレームワークみたいな呼び方や、数行でも説明があったほうが良い気がしました

## 感想

https://twitter.com/yamap_55/status/1737257155055796361

**Comment by aion0721** [comment]
コメントありがとうございます、励みになります！
Errataにて表記するとともに、種々第二版にて対応させていただきます！

**Comment by aion0721** [comment]
第二版として修正済。v1.0のエラータとして作成予定。
